# Generated by Django 3.0.4 on 2020-08-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoitment',
            new_name='Appointment',
        ),
    ]
