# Generated by Django 3.0.4 on 2020-08-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20200813_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time1',
            field=models.TimeField(),
        ),
    ]
