# Generated by Django 3.0.4 on 2020-09-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200825_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='paitent',
            new_name='patient',
        ),
    ]
